window.blogPosts = [
  {
    "id": "verhoog-je-zichtbaarheid-in-ai-overzichten",
    "title": "Verhoog je zichtbaarheid in AI-overzichten",
    "description": "Als je marketingstrategie nog steeds alleen om Google draait, loop je het risico onzichtbaar te zijn voor je klanten. Wat? 🙃",
    "category": "SEO",
    "author": "Wouter Naber",
    "date": "2025-09-07",
    "readCount": 0,
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757244049303-627635481.jpg",
    "heroImageAlt": "Verhoog je zichtbaarheid in AI-overzichten",
    "slug": "verhoog-je-zichtbaarheid-in-ai-overzichten",
    "heroImageThumb": "images/heroes/verhoog-je-zichtbaarheid-in-ai-overzichten-thumb.jpg",
    "heroImageDesktop": "images/heroes/verhoog-je-zichtbaarheid-in-ai-overzichten-desktop.jpg"
  },
  {
    "id": "instagram-seo-meer-dan-een-pretty-picture",
    "title": "Instagram SEO: Meer dan een Pretty Picture",
    "description": "De tijd dat Instagram alleen draaide om esthetische plaatjes is voorbij. In 2025 is Instagram, net als TikTok, Amazon, Reddit en ChatGPT, een volwaardige <em>zoekmachine</em> waar consumenten cruciale koopbeslissingen nemen. Als je marketingstrategie nog steeds uitsluitend gericht is op Google, mis je een gigantisch deel van je potentiële klanten. Dit is de 'Google-val': zelfs als je het Google-spel wint, verlies je klanten omdat hun beslissingen elders vallen.",
    "category": "SEO",
    "author": "Wouter Naber",
    "date": "2025-09-06",
    "readCount": "4314",
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757261594354-386497953.jpg",
    "heroImageAlt": "Instagram SEO: Meer dan een Pretty Picture",
    "slug": "instagram-seo-meer-dan-een-pretty-picture",
    "heroImageThumb": "images/heroes/instagram-seo-meer-dan-een-pretty-picture-thumb.jpg",
    "heroImageDesktop": "images/heroes/instagram-seo-meer-dan-een-pretty-picture-desktop.jpg"
  },
  {
    "id": "tiktok-seo-van-virale-dansjes-naar-serieuze-zoekmachine-optimalisatie",
    "title": "TikTok SEO: van virale dansjes naar serieuze zoekmachine-optimalisatie",
    "description": "TikTok is allang geen platform meer waar alleen tieners dansjes doen. In 2025 is TikTok uitgegroeid tot een volwaardige zoekmachine waar consumenten actief informatie, inspiratie en koopbeslissingen vinden. Als je SEO-strategie nog steeds alleen leunt op Google, loop je keihard omzet mis. Je klanten zoeken – en beslissen – elders.",
    "category": "SEO",
    "author": "Wouter Naber",
    "date": "2025-09-07",
    "readCount": 0,
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757262765549-164929561.jpg",
    "heroImageAlt": "TikTok SEO: van virale dansjes naar serieuze zoekmachine-optimalisatie",
    "slug": "tiktok-seo-van-virale-dansjes-naar-serieuze-zoekmachine-optimalisatie",
    "heroImageThumb": "images/heroes/tiktok-seo-van-virale-dansjes-naar-serieuze-zoekmachine-optimalisatie-thumb.jpg",
    "heroImageDesktop": "images/heroes/tiktok-seo-van-virale-dansjes-naar-serieuze-zoekmachine-optimalisatie-desktop.jpg"
  },
  {
    "id": "google-ai-mode-wordt-het-de-standaard-ervaring-in-search",
    "title": "Google AI Mode: Wordt het de standaard ervaring in Search?",
    "description": "Logan Kilpatrick, lead product manager bij Google, zei vrijdag dat Google’s AI Mode binnenkort de “default” zoekervaring wordt in Google Search. In mei 2025 kondigde Liz Reid, hoofd van Google Search, al aan dat AI Mode de toekomst van Search is. En nu lijkt die toekomst dichterbij dan ooit – of toch niet?",
    "category": "SEO",
    "author": "Wouter Naber",
    "date": "2025-09-09",
    "readCount": "4324",
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757413653103-170705650-desktop.jpg",
    "heroImageAlt": "Google AI Mode: Wordt het de standaard ervaring in Search?",
    "slug": "google-ai-mode-wordt-het-de-standaard-ervaring-in-search",
    "heroImageThumb": "images/heroes/google-ai-mode-wordt-het-de-standaard-ervaring-in-search-thumb.jpg",
    "heroImageDesktop": "images/heroes/google-ai-mode-wordt-het-de-standaard-ervaring-in-search-desktop.jpg"
  },
  {
    "id": "wanneer-een-merk-zijn-ziel-verliest",
    "title": "Wanneer een merk zijn ziel verliest",
    "description": "In het tijdperk van ChatGPT, CRM-flows en conversiepixels praten merken harder dan ooit, maar zeggen ze minder dan ze vroeger deden. We hebben de wetenschap van segmentatie geperfectioneerd, maar zijn de kunst van connectie vergeten.",
    "category": "Content Marketing",
    "author": "Lasse Botman",
    "date": "2025-09-09",
    "readCount": "778",
    "authorAvatar": "images/writers/Lasse Botman.png",
    "heroImage": "uploads/header-1757420101756-527600433-desktop.jpg",
    "heroImageAlt": "Wanneer een merk zijn ziel verliest",
    "slug": "wanneer-een-merk-zijn-ziel-verliest",
    "heroImageThumb": "images/heroes/wanneer-een-merk-zijn-ziel-verliest-thumb.jpg",
    "heroImageDesktop": "images/heroes/wanneer-een-merk-zijn-ziel-verliest-desktop.jpg"
  },
  {
    "id": "van-ai-hype-naar-ai-voorsprong",
    "title": "Van AI-hype naar AI-voorsprong",
    "description": "AI is overal. Elke scroll op LinkedIn voelt hetzelfde: weer een magisch voorbeeld, weer een belofte. Maar wie voorbij de buzz kijkt, ziet de echte uitdaging. Niet wát AI kan, maar hóe je er structureel voordeel mee bouwt. In dit stuk lees je hoe bedrijven van hype naar gewoonte gaan. En hoe AI onzichtbaar, maar onmisbaar wordt.",
    "category": "Digital Marketing",
    "author": "Wouter Naber",
    "date": "2025-09-02",
    "readCount": "423",
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757426355043-462978979-desktop.jpg",
    "heroImageAlt": "Van AI-hype naar AI-voorsprong",
    "slug": "van-ai-hype-naar-ai-voorsprong",
    "heroImageThumb": "images/heroes/van-ai-hype-naar-ai-voorsprong-thumb.jpg",
    "heroImageDesktop": "images/heroes/van-ai-hype-naar-ai-voorsprong-desktop.jpg"
  },
  {
    "id": "online-marketing-in-de-bouw-springplank-naar-digitaal-succes",
    "title": "Online Marketing in de Bouw: Springplank naar Digitaal Succes",
    "description": "De bouw loopt achter in digitalisering. Toch zoeken klanten steeds vaker online naar bewijs van waarde. Op LinkedIn concurreren meer dan 8.000 bouwbedrijven om aandacht. Zonder sterke digitale aanwezigheid raak je onzichtbaar. Klanten kopen geen jargon, maar harde resultaten. Lagere kosten, duurzaamheid en kwaliteit die je kunt aantonen.",
    "category": "Digital Marketing",
    "author": "Wouter Naber",
    "date": "2025-09-09",
    "readCount": 0,
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757427824064-434544161-desktop.jpg",
    "heroImageAlt": "Online Marketing in de Bouw: Springplank naar Digitaal Succes",
    "slug": "online-marketing-in-de-bouw-springplank-naar-digitaal-succes",
    "heroImageThumb": "images/heroes/online-marketing-in-de-bouw-springplank-naar-digitaal-succes-thumb.jpg",
    "heroImageDesktop": "images/heroes/online-marketing-in-de-bouw-springplank-naar-digitaal-succes-desktop.jpg"
  },
  {
    "id": "seo-bureau-alkmaar-van-zichtbaarheid-naar-impact",
    "title": "SEO Bureau Alkmaar: van zichtbaarheid naar impact",
    "description": "Ben je op zoek naar een SEO bureau in Alkmaar dat verder kijkt dan rankings? Dan zit je goed. Traditionele SEO is niet meer genoeg. Met AI-zoekmachines zoals Google AI Overviews, Copilot en ChatGPT verschuift de vraag van “ben je vindbaar?” naar “word je vertrouwd?”. Het verschil tussen zichtbaar en onzichtbaar bepaalt of je meedoet in deze nieuwe realiteit.",
    "category": "SEO",
    "author": "Wouter Naber",
    "date": "2025-09-09",
    "readCount": "936",
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757429674621-786906562-desktop.jpg",
    "heroImageAlt": "SEO Bureau Alkmaar: van zichtbaarheid naar impact",
    "slug": "seo-bureau-alkmaar-van-zichtbaarheid-naar-impact",
    "heroImageThumb": "images/heroes/seo-bureau-alkmaar-van-zichtbaarheid-naar-impact-thumb.jpg",
    "heroImageDesktop": "images/heroes/seo-bureau-alkmaar-van-zichtbaarheid-naar-impact-desktop.jpg"
  },
  {
    "id": "google-tag-manager-installeren",
    "title": "Google Tag Manager installeren",
    "description": "We zetten Google Tag Manager correct op je site of app. Met een solide basis haal je maximale waarde uit je data.",
    "category": "Digital Marketing",
    "author": "Wouter Naber",
    "date": "2025-09-10",
    "readCount": 0,
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757503733010-775135530-desktop.jpg",
    "heroImageAlt": "Google Tag Manager installeren",
    "slug": "google-tag-manager-installeren",
    "heroImageThumb": "images/heroes/google-tag-manager-installeren-thumb.jpg",
    "heroImageDesktop": "images/heroes/google-tag-manager-installeren-desktop.jpg"
  },
  {
    "id": "ga4-koppelen-via-gtm",
    "title": "GA4 koppelen via GTM",
    "description": "Wij koppelen GA4 via Google Tag Manager en zorgen dat je events correct doorkomen. Betrouwbare data vanaf dag één.",
    "category": "Analytics",
    "author": "Wouter Naber",
    "date": "2025-09-10",
    "readCount": "432",
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757504139562-818057750-desktop.jpg",
    "heroImageAlt": "GA4 koppelen via GTM",
    "slug": "ga4-koppelen-via-gtm",
    "heroImageThumb": "images/heroes/ga4-koppelen-via-gtm-thumb.jpg",
    "heroImageDesktop": "images/heroes/ga4-koppelen-via-gtm-desktop.jpg"
  },
  {
    "id": "google-tag-manager-uitleg",
    "title": "Google Tag Manager uitleg",
    "description": "Begrijp wat GTM is, waarom het onmisbaar is en hoe je het gebruikt om meer grip te krijgen op je data.",
    "category": "Google Tag Manager",
    "author": "Wouter Naber",
    "date": "2025-09-10",
    "readCount": "677",
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757504427917-694022495-desktop.jpg",
    "heroImageAlt": "Google Tag Manager uitleg",
    "slug": "google-tag-manager-uitleg",
    "heroImageThumb": "images/heroes/google-tag-manager-uitleg-thumb.jpg",
    "heroImageDesktop": "images/heroes/google-tag-manager-uitleg-desktop.jpg"
  },
  {
    "id": "google-ads-tracking-via-gtm",
    "title": "Google Ads tracking via GTM",
    "description": "Meet je conversies correct via Google Tag Manager en maak je campagnes direct effectiever.",
    "category": "Google Tag Manager",
    "author": "Wouter Naber",
    "date": "2025-09-10",
    "readCount": "321",
    "authorAvatar": "images/writers/Wouter Naber.jpg",
    "heroImage": "uploads/header-1757504558027-51711730-desktop.jpg",
    "heroImageAlt": "Google Ads tracking via GTM",
    "slug": "google-ads-tracking-via-gtm",
    "heroImageThumb": "images/heroes/google-ads-tracking-via-gtm-thumb.jpg",
    "heroImageDesktop": "images/heroes/google-ads-tracking-via-gtm-desktop.jpg"
  }
];